### ISSUE TITLE
How do you embed code like that in the mind maps?

### ISSUE THREAD

**Issue by nikivdev** [chrisbeach/mindmaps-scala-java#1]
![2017-03-22 at 14 23](https://cloud.githubusercontent.com/assets/6391776/24199768/25afb1e4-0f0b-11e7-8f79-3aac0f3a613d.png)

**Comment by chrisbeach** [comment]
I simply copy/pasted from my IDE (IntelliJ) and changed the node format to have a square border. Nothing clever going on :-)
